export const MAX_RADIUS = 150;
export const MAX_SPACE_BETWEEN_CIRCLES = 300;

export const PROPORTIONAL_SPACE_TO_RADIUS_RATIO = 1.1;
export const SPACE_BETWEEN_CIRCLE_AND_ARROW_TO_CIRCLE_AND_CIRCLE_RATIO = 0.17;

export const VIEWPORT_PADDING = 50;
